---
title: Lolware
email: technion@lolware.net
author: Technion
keep_files: ["kerbal", ".well-known"]
author_github: hugocarreira
port: 4567
host: 0.0.0.0
destination: "/var/www/html"
description: |
    Blogging on development and insecurities
baseurl: "/"
url: "https://lolware.net"
paginate: 6
home_bgfile: somuchwin.png
markdown: redcarpet
highlighter: rouge
redcarpet:
  extensions: ["strikethrough", "tables", "fenced_code_blocks"]
produrl: https://lolware.net
cssbuild: prod
plugins:
  - jekyll-paginate
  - redcarpet
  - rouge
  - jekyll-sitemap
exclude: ['vendor', 'node_modules', 'buildcss.js', 'yuicompressor-2.4.8.jar',
         'Gemfile', 'Gemfile.lock' ]
sass:
  sass_dir: _sass
